CREATE TABLE IF NOT EXISTS styles (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS musicians (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	year INTEGER NOT NULL,
	style_id INTEGER REFERENCES styles(id) NOT NULL
);

CREATE TABLE IF NOT EXISTS albums (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	year INTEGER NOT NULL,
	musician_id INTEGER REFERENCES musicians(id) NOT NULL
);
CREATE TABLE IF NOT EXISTS songs (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	duration INTEGER NOT NULL,
	album_id INTEGER REFERENCES albums(id) NOT NULL
);